# Generated by Django 4.1.9 on 2023-06-07 18:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trade_dashboard', '0007_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='trade_dashboard.transaction'),
            preserve_default=False,
        ),
    ]
