# Generated by Django 4.1.9 on 2023-06-07 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_dashboard', '0008_payment_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='trade_dashboard.transaction'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='trade_dashboard.wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='trade_dashboard.wallet'),
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trade_dashboard.payment')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trade_dashboard.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trade_dashboard.wallet')),
            ],
        ),
    ]
