# Generated by Django 4.1.9 on 2023-06-07 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trade_dashboard', '0009_alter_payment_transaction_alter_payment_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
